#!/bin/sh

# download the source page
wget -q http://www.bay12games.com/dwarves/

# find version/date
version=$(grep -Pom 1 "\d+\.\d+\.\d+" index.html)
date=$(grep -Pom 1 "\((.+)\)\<\/s" index.html | cut -c 2- | rev | cut -c 5- | rev)

# find package names
winPkg=$(grep -Po "df_\d+_\d+_win\.zip" index.html)
linPkg=$(grep -Po "df_\d+_\d+_linux\.tar\.bz2" index.html)
osxPkg=$(grep -Po "df_\d+_\d+_osx\.tar\.bz2" index.html)

# build URLs
dlUrl="http://www.bay12games.com/dwarves/"
winUrl=$dlUrl$winPkg
linUrl=$dlUrl$linPkg
osxUrl=$dlUrl$osxPkg

# echo the JSON
echo "[ {
  \"date\": \"$date\",
  \"version\": \"$version\",
  \"windows_x86\": \"$winUrl\",
  \"linux_x86\": \"$linUrl\",
  \"mac_x86\": \"$osxUrl\"
} ]"

# remove source page
rm index.html
